# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "57f083d21cc50b6c2e9512b6193ac738"
name = "TrustLayer"
application_url = "https://trust-layer-chi.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products,write_metaobjects,write_metaobject_definitions"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products"
  topics = [ "products/create", "products/delete", "products/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop"
  topics = [ "shop/update" ]

[auth]
redirect_urls = [ "https://trust-layer-chi.vercel.app/api/auth" ]

[app_proxy]
url = "https://trust-layer-chi.vercel.app/apps/proxy"
subpath = "trust-layer"
prefix = "apps"
